### ISSUE TITLE
Difference between your work and DTC ?

### ISSUE THREAD

**Issue by TiankaiHang** [YichiZhang98/DTML#1]
Hi, thanks for your nice work! That's very interesting and meaningful.

I have several questions.
What's your key difference between [Semi-supervised medical image segmentation through dual-task consistency] and your work.
The idea and the diagram are so similar. Maybe a better and more clear statement about the difference should be given?

Best.

**Comment by YichiZhang98** [comment]
Hi Tiankai,

Thanks for your interest in our work. 
Our work and DTC both focus on introducing distance maps into SSL. The key difference is that, in DTC, the segmentation task and regression task share the same network backbone, while in our work, we use two individual networks for different tasks. 
Since each network starts from a different learning condition, they can learn different representations of the segmentation task. Following the mutual learning manner, we found that the knowledge transfer between dual-task learning can further improve the performance.

Best regards

**Comment by TiankaiHang** [comment]
Got that, thanks for your kind reply!
