### ISSUE TITLE
cannot reproduce the results

### ISSUE THREAD

**Issue by Huiimin5** [YichiZhang98/DTML#3]
Hi, thank you so much for releasing your code!

The best performance I can obtain after training with your code on LA dataset is 0.89697391 0.81447848 7.44489285 1.85291552. I have tried all iterations saved through the training process. Do you have any idea why this performance drop comes from? By the way, may I know your python, pytorch and cuda versions?

**Comment by YichiZhang98** [comment]
Hi,
Thanks for your interest in our work. Our implementation is based on CUDA 10.2, python 3.8 and torch 1.7.0.
In our work, the experiments are performed on the same machine several times and the results are consistent under the same setting. Possibly, the results may vary slightly due to the difference of machine/environments.
